#! /bin/sh

PORTAGE=/usr/portage

cp_pkg () {
	mkdir -p "$1" &&
	rm -rf "$1/$2" &&
	cp -r "$PORTAGE/$1/$2" "$1"
}

cp_pkg sys-devel gcc &&
cp_pkg sys-devel binutils &&
cp_pkg sys-libs  glibc &&

mkdir -p eclass &&
cp "$PORTAGE"/eclass/toolchain* eclass/ &&

git add -A sys-libs eclass sys-devel &&
git commit -m 'Import on '"`date`"'.'
